// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbiqkrajvvgetgomwqnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaXFrcmFqdnZnZXRnb213cW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTk5NzksImV4cCI6MjA2NTQ3NTk3OX0.m5so0HhdD9WQfvAv8EltUsB3MBmrNnD9gfNZL4F9tu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);